services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "1434:1433"

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__Default: "Server=db;Database=warehouse;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True"
      Jwt__Key: "${JWT_KEY}"
      Jwt__Issuer: "WarehouseApi"
      Jwt__Audience: "WarehouseApiUsers"